### Crear un nuevo paquete
POST http://localhost:9002/api/paquete HTTP/1.1
Content-Type: application/json

{
    "destino": "Santa Marta",
    "actividad": "Buceo",
    "numeroPersonas": 6,
    "categoria": "Paquete 2",
    "precio": 1000000,
    "transporte": "Avion",
    "comida": "todoincluido",
    "imagen": "http://www.ejemplo.com/imagen.jpg"
}


###

### Obtener todos los paquetes
GET http://localhost:9002/api/paquete HTTP/1.1
###



### Actualizar un paquete específico por ID
PUT http://localhost:9002/api/paquete/67369650e84a0cc43752579e HTTP/1.1
Content-Type: application/json

{
    "destino": "San Andres",
    "actividad": "Buceo",
    "numeroPersonas": 4,
    "categoria": "paquete3",
    "precio": "1620000",
    "transporte":  "avion",
    "comida": "almuerzo incluido"
}
###

### Eliminar un paquete específico por ID
DELETE http://localhost:9002/api/paquete/67478971291808bb22cfd131 HTTP/1.1


























